name: smart_home
description: A home automation smart application.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  awesome_circular_chart: ^1.1.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dotted_border: ^2.1.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.1.0
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.3
  image_picker: ^1.1.2
  lottie: ^3.1.2
  provider: ^6.1.5
  sleek_circular_slider: ^2.0.1
  sliding_up_panel: ^2.0.0+1
  syncfusion_flutter_charts: ^26.2.10
  table_calendar: ^3.1.3
  archive: ^3.6.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.4
  flutter_test:
    sdk: flutter

dependency_overrides:
  win32: ^5.13.0
  path: 1.9.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_1024.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/favourite.png
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/images/weather/
    - assets/images/settings/
    - assets/icons/svg/
    - assets/Lottie/
    - assets/icons/menu_icons/
    - assets/images/movies/

  fonts:
    - family: "Noto Sans"
      fonts:
        - asset: "assets/fonts/NotoSans-Bold.ttf"
          style: "normal"
        - asset: "assets/fonts/NotoSans-Regular.ttf"
          style: "normal"
    - family: "Poppins"
      fonts:
        - asset: "assets/fonts/Poppins-700.ttf"
          style: "normal"
          weight: 700
    - family: ABeeZee
      fonts:
        - asset: assets/fonts/ABeeZee-Italic.ttf
          style: italic
        - asset: assets/fonts/ABeeZee-Regular.ttf
          style: normal
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lexend-ExtraLight.ttf
          weight: 200