// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCToC9z2MjBAJ4vYsN7ts-_oRlcirjKDJY',
    appId: '1:660074262019:web:f05e3c5c58e2ca26436836',
    messagingSenderId: '660074262019',
    projectId: 'flutterfire-ui-codelab-77ef3',
    authDomain: 'flutterfire-ui-codelab-77ef3.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-77ef3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw1qW-TufkYV_0_FjyLvkmWtNc3bRPz9I',
    appId: '1:660074262019:android:aed40eaaf001c6a8436836',
    messagingSenderId: '660074262019',
    projectId: 'flutterfire-ui-codelab-77ef3',
    storageBucket: 'flutterfire-ui-codelab-77ef3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGMMhMPk_eHxYA00FUJV3qo-oHxOrY5oY',
    appId: '1:660074262019:ios:e10239a49cb1dd61436836',
    messagingSenderId: '660074262019',
    projectId: 'flutterfire-ui-codelab-77ef3',
    storageBucket: 'flutterfire-ui-codelab-77ef3.firebasestorage.app',
    iosClientId: '660074262019-f048obt9r5ar6nuk4eakhr4b71f34ttb.apps.googleusercontent.com',
    iosBundleId: 'com.smarthome.khoa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGMMhMPk_eHxYA00FUJV3qo-oHxOrY5oY',
    appId: '1:660074262019:ios:e10239a49cb1dd61436836',
    messagingSenderId: '660074262019',
    projectId: 'flutterfire-ui-codelab-77ef3',
    storageBucket: 'flutterfire-ui-codelab-77ef3.firebasestorage.app',
    iosClientId: '660074262019-f048obt9r5ar6nuk4eakhr4b71f34ttb.apps.googleusercontent.com',
    iosBundleId: 'com.smarthome.khoa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCToC9z2MjBAJ4vYsN7ts-_oRlcirjKDJY',
    appId: '1:660074262019:web:e17f1e50c1cdd65e436836',
    messagingSenderId: '660074262019',
    projectId: 'flutterfire-ui-codelab-77ef3',
    authDomain: 'flutterfire-ui-codelab-77ef3.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-77ef3.firebasestorage.app',
  );

}