// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQqK9qTbHpYzD8K9QHl5j9kKXJm3v1nYs',
    appId: '1:244911112023:web:a1b2c3d4e5f6g7h8i9j0k1',
    messagingSenderId: '244911112023',
    projectId: 'chat-47899',
    authDomain: 'chat-47899.firebaseapp.com',
    storageBucket: 'chat-47899.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgdbQgGl8c2UgJX8TwE1EhZHocD5AiUMQ',
    appId: '1:244911112023:android:1e022a783d5b937ba60812',
    messagingSenderId: '244911112023',
    projectId: 'chat-47899',
    databaseURL: 'https://chat-47899-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-47899.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACgsismEZLZY6_okEz_OnIEBYJRnayqco',
    appId: '1:244911112023:ios:305f9963e21204a0a60812',
    messagingSenderId: '244911112023',
    projectId: 'chat-47899',
    databaseURL: 'https://chat-47899-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-47899.appspot.com',
    iosClientId: '244911112023-1f01863ig5sd8rsdgehcpk2al8jk1u6o.apps.googleusercontent.com',
    iosBundleId: 'com.smarthome.khoa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl4hJk7uI8gF5dC2aN3eQ6wX9zP0oM1vB',
    appId: '1:244911112023:ios:x3y4z5a6b7c8d9e0f1g2h3',
    messagingSenderId: '244911112023',
    projectId: 'chat-47899',
    storageBucket: 'chat-47899.appspot.com',
    iosClientId: '244911112023-abcdefghijklmnopqrstuvwxyz123456.apps.googleusercontent.com',
    iosBundleId: 'com.smarthome.khoa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQqK9qTbHpYzD8K9QHl5j9kKXJm3v1nYs',
    appId: '1:244911112023:web:w4x5y6z7a8b9c0d1e2f3g4',
    messagingSenderId: '244911112023',
    projectId: 'chat-47899',
    authDomain: 'chat-47899.firebaseapp.com',
    storageBucket: 'chat-47899.appspot.com',
  );

}