// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDag4Tczho4cK1RzZzo_dRoOQdQNJ18EA',
    appId: '1:954956298567:web:a09911feb2904860f43462',
    messagingSenderId: '954956298567',
    projectId: 'chatapp-54676',
    authDomain: 'chatapp-54676.firebaseapp.com',
    storageBucket: 'chatapp-54676.firebasestorage.app',
    measurementId: 'G-RCCD3SYYBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk5qCUJ-zXJ0ekvgjb9abE1zRIxHEAsC8',
    appId: '1:954956298567:android:83814e9a11c5bd6cf43462',
    messagingSenderId: '954956298567',
    projectId: 'chatapp-54676',
    storageBucket: 'chatapp-54676.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZh-sOoZ9lynduFnEClc8P7PcqE3TpJf4',
    appId: '1:954956298567:ios:7bede964f716da75f43462',
    messagingSenderId: '954956298567',
    projectId: 'chatapp-54676',
    storageBucket: 'chatapp-54676.firebasestorage.app',
    iosClientId: '954956298567-tgthr07qmv8iuskg9u4onsm4ksr224rv.apps.googleusercontent.com',
    iosBundleId: 'com.smarthome.khoa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZh-sOoZ9lynduFnEClc8P7PcqE3TpJf4',
    appId: '1:954956298567:ios:7bede964f716da75f43462',
    messagingSenderId: '954956298567',
    projectId: 'chatapp-54676',
    storageBucket: 'chatapp-54676.firebasestorage.app',
    iosClientId: '954956298567-tgthr07qmv8iuskg9u4onsm4ksr224rv.apps.googleusercontent.com',
    iosBundleId: 'com.smarthome.khoa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDag4Tczho4cK1RzZzo_dRoOQdQNJ18EA',
    appId: '1:954956298567:web:63de4f1656a51da2f43462',
    messagingSenderId: '954956298567',
    projectId: 'chatapp-54676',
    authDomain: 'chatapp-54676.firebaseapp.com',
    storageBucket: 'chatapp-54676.firebasestorage.app',
    measurementId: 'G-149MCP3R83',
  );

}